### ISSUE TITLE
CyberGIS

### ISSUE THREAD

**Issue by jakobzhao** [jakobzhao/geog595#3]

**Comment by zwguo95** [comment]
I enjoy the crucial question brought up by Feenberg (1992): why has democracy not been extended to technically mediated domains of social life? The author argues that technology per se does not exclude democracy, but the way it has been used unwittingly blocks democratization. 
This reminds me of some sorts of new interactions between citizens and state with the uprising technology. Citizens seem to be more disadvantaged under the amplifying asymmetry compared to governments in terms of information. For instance, governments, equipped with unprecedented capabilities to monitor, track and surveil individual people (especially in cooperation with big tech companies), are likely to abuse their power. 
What deserves our caution as well is the spread of technology across the world, which means state-and-society practices in other countries can also be reshaped by learning technology models from others. For example, Chinese companies have been exporting AI surveillance technology to over 50 countries, packaged as part of the Belt and Road Initiative in particular, and have set up smart cities featuring extensive digital surveillance in countries like Kenya and Pakistan. 
However, I would say I am more of an optimist about the accommodation and reconciliation of technology and democratic values in the future. We have observed some strategic social resistance against the threatening consequences of technology to democratic values. For example, protesters wear masks to shield themselves from surveillance and apply social media not only to organize their activities but to arouse international attention and express opposition. We have also seen the innovative inclusion of digital citizenship in the K-12 curriculum, where students are educated to practice democratic values through their daily experiences on the Internet. 
All in all, I side with the author that technology can support many types of technological civilization and will someday be incorporated into a more democratic society than ours.

**Comment by erykwaligora** [comment]
![image](https://user-images.githubusercontent.com/59897808/72394709-060e3e80-36ec-11ea-9600-8aac2e1d0c9e.png)

**Comment by erykwaligora** [comment]
All of the readings this week, more or less, emphasized the need to consider the placement of values within the technological evolution of our time. I found this interesting since most of these readings are decades old. There is a certain cautionary tale to them that echoes into the present. All of which are relevant to the study of GIS, of course Wang’s in particular. He explains that geographers and GIS is a linkage between technology and the greater human social network, but is cautious, that with the degree of separation using enhanced technology such as CyberGIS, we need to be aware of the values to uphold i.e. not to group inappropriately, analyzing the context of a particular occurrence, etc. Another reading that stood out to me was Feenberg’s piece. His focus on the democratization of technology made me think about today’s society’s obsession with optimization and efficiency culture, using technologies or information such as apps or “life hacks”. Are we really becoming more efficient? Some argue that we will always find more work and distraction regardless of technology’s assistance to optimize that work. There’s a great [podcast episode](https://www.stitcher.com/podcast/the-ezra-klein-show/e/60197403?autoplay=true) about this subject that I highly recommend. This topic also reminds me of Cal Newport’s book “Deep Work”. Clearly this subject of technology and human values is on people’s minds (especially) today. Going back to Feenberg, while I understand his argument, he doesn’t provide enough specifics to his point and instead generalizes that in order for technology to democratize there need to show social “initiative and participation”. This is a very ‘rise up’ way of thinking that I don’t think can support a broader social change that he claims is necessary. I’m interested in discussing more about his ideas. An anecdote to this week’s readings reminds me of last quarter in ‘JSIS 555 Cybersecurity and International Studies’. Our class had a guest speaker from Google’s Trust and Safety department. She said something at the conclusion of her talk that really stuck with me. She said, “technology won’t solve all the problems”.

**Comment by jouho** [comment]
In _The Social Impact of Technological Change_ the author Mesthene discussed some of the contemporary issues of technology. He argues that we are disposing a considerable amount of physical power and we are beginning to act and think upon it. Therefore, he thinks we are the first to free ourselves from the tyranny of nature. However, on the other hand, the power has shifted to metaphysical elements such as government, laws, and even technologies. This reminds me of classic Sci-Fi novels and movies where machines and robots take over our life, like in Terminator. One thing that we should realize is that technology not only possesses physical and functional power, but it also possesses authority within. This means that modern technology is so developed that it can control, influence, denote a power or right to direct the actions or thoughts of others. For example, I would more likely trust what my Google map shows me the closest way to a grocery store than a stranger telling me where it is instead, regardless of whether if Google map gives true or false information. Surprisingly, Mesthene briefly talks about machines taking over our life. He says "the more machines can take over what we do, the more we can do what machines cannot do". If what he says is true, are we going to be taken over by machines and will building machines be the only job human is going to perform in the future? I thought it is particularly interesting that the author talked on this topic since this paper was written a couple of decades ago, in a time when the concept of artificial intelligence was not yet broadly known. Whether Mesthene's point on today's role of technology is true or false, it is clear that we need to think critically and manage a wise relationship between us and technology.
