### ISSUE TITLE
GeoVisualization

### ISSUE THREAD

**Issue by jakobzhao** [jakobzhao/geog595#6]

**Comment by erykwaligora** [comment]
My understanding of this week’s readings on GeoVisualization contained three important elements for discussion; (1) methodology, (2) transdisciplinary representation, and (3) how geography and the use of mapping is critical to understanding our past, present, and future through effective utilization. 

MacEachren combines the first two points in his piece by proposing that “progress requires fundamental break-throughs in both geovisualization and its integration with other methods for geospatial knowledge construction”. He notes that as 80% of all digital data represented today [2013] includes geospatial references, it is critical to understand how these images are represented and how information is properly translated. He laments in saying that geospatial information does not properly address societal needs due to the lack in diverse methodology, pertaining more to the humanities. In many ways, this concern translates to the challenge of map-based information sharing we see today [2020]. Roth’s literature review and recommendations possess the most compelling insight into how to address these challenges. The focus of his argument is on design, whereby he identifies narrative, genre, and trope to explain how these elements can enhance the visual storytelling of geography by integrating interdisciplinary methods. His extensive breakdown of visual story telling in relation to geography is most relevant to the challenge cartographers have today, which is not only executing accurate and ethical information, but for it to be engaging, sharable, and accessible to a wider audience. With better storytelling, maps can reflect not only the special data but the human experience between the numbers. 

I enjoyed the juxtaposition of the Knowles and Kent pieces. While Knowles focused on how mapping can be used to better understand the human experience in historical events, such as the Holocaust, Kent takes us forward from post-WWII into the present and future of geospatial communications and its viability in information systems. As a grandchild of Holocaust survivors and a Holocaust studies minor in undergrad, the Knowles piece was particularly meaningful. I can understand what she means when she states that the “field mainly attracts historians, literary and religious scholars, psychologists, etc.”. I think bridging this gap with GIS is utterly important to understand the issues of past experience that these other fields cannot fully address on their own. This is especially important in attempting to map the complexities of space and memory. I thought this element of the reading was very intriguing. Additionally, GIS mapping of physical movements and locational incidents to provide new insight on difficult questions. Notably, is the example of determining when “murder” became “genocide”, using the Lithuania database case. Kent then draws attention to the challenges facing cartographers from post-WWII era propaganda to today’s global digital misinformation on social media. He provides a great deal of attention to the importance of how cartographers need to more effectively utilize maps in this new environment, but how this also presents challenges as more and more cartographers base utilization on social media user feedback. He explains, “this is especially important, when map-makers seek to make curiosity-driven maps for the purposes of entertainment at a time when the boundary between entertainment and information is blurring.” 

While this week’s readings on mapping and geovisualization do not directly inform my own research, the underlying implications on methodology, transdisciplinary representation, and effective use of data in compelling yet informative ways is helpful to my thought process.

**Comment by tpmccrea** [comment]
The readings this week were linked in their shared focus on visualization and visual-storytelling, and articulating a Humanistic or Human centered approach to geospatial visualization. The pieces discussed new communication paradigms, alternatives to GIS for spatial visualization, and techniques for narrative storytelling using geospatial data, and noted the challenges of working with spatial data from across disciplines, time, and spatial scales. Two pieces that stood out to me in particular were; Inductive Visualization: A Humanistic Alternative to GIS (Knowles, Westerveld & Strom, 2015) & Research Challenges in Geovisualization (MacEachren & Kraak, 2001). Knowles, et al write this about GIS as a tool, “GIS is ideal for studying representations of space but has limited utility for studying spatial practice.” (pg. 237). This really struck me, along with their amazing visualizations. While there are methods for using GIS to move beyond merely representation of spatial boundaries and displaying data within the polygons, I am thinking of cartograms for instance. I agree with the criticism in the piece related to GIS not being able to capture spatial practice. Several of the data visualizations in the piece were incredibly interesting (see attached), and truly showcased what the author's intentions were in laying out various methods for displaying and relaying to the viewer the entire human experience of the individuals whose lives are being mapped.            

Two data visualizations from the Knowles piece (Figure 3 & 5) exemplify human, non-GIS developed representations of spatial-temporal data. Figure 5 is striking in its simplicity, but the depth of information conveyed is immense. Visualizing a forced march in this way is something I have never seen before and it has me thinking about the possibilities and methods for showing movement, place and individual experiences. 
<img width="433" alt="Figure 3 (knowles, et al)" src="https://user-images.githubusercontent.com/59938560/74293244-0c91d500-4cef-11ea-8b43-8a4ad5776189.png">
<img width="195" alt="Figure 5 (knowles, et al)" src="https://user-images.githubusercontent.com/59938560/74293261-17e50080-4cef-11ea-9ccd-d75e60f6a705.png">

The forced march figure also relates to the call from Roth (forthcoming) to introduce and showcase narrative, and storytelling in our spatial practice. Focusing on human scale, human-centered visualizations of spatial data can be immersive and can communicate a more comprehensive, and useful story to the user than a map alone can. With the growth of geospatial technology, ever increasing abundance of  personal data, and a general democratization of mapping and spatial practice, I think it is only becoming more important that we integrate a multi-disciplinary, integrative humanistic-based approach to mapping, manipulating and displaying spatial data visualizations.

**Comment by angellinn** [comment]
This week's readings discuss the challenges as well as the unlimited potential of turning data into information and into knowledge. And the ultimate goal is to develop both theories and practices that facilitate knowledge construction through visual exploration and analysis of geospatial data, along with the visual tools needed to support knowledge retrieval, syntheses, and usage. 

In  "Research Challenges and Geovisualization" (MacEachren & Kraak, 2001,) the authors call for action  to develop more capable and efficient tools for geospatial analysis and presentation. While 80% of all digital data generated today included geospatial referencing, visualization is not being taken advantage of to exploit the full potential of geospatial data, nor to take georeferencing as a mechanism for fusing data from diverse sources. The authors then present three reasons why this is an issue worth taken care of. First, since geospatial data are inherently structured in two/three/four dimensions while they are often unstructured in others, different approaches must be developed for integrated visual analysis of these data. Second, while the names of objects in geospatial databases are often meaningful and can draw critical insights, the match between geographic names and objects is complicated and vary explicitly. Third, geospatial data are typically collected at multiple scales, which makes geospatial analysis particularly challenging. 

With an increasing societal need of both scientific progress and application of geospatial information, breakthroughs in geovisualization and analytical methods are necessary. While addressing the research challenges directly is the more achievable part, meeting and resolving them is a more adversary effort.

**Comment by jouho** [comment]
This week's reading reminded me of one of the first week's readings written by Heidegger. He was questioning 'what is the _essense_ of technology?'. I personally thought this concept of asking the essence could be applied to this week's reading. 

As I went through Alexander J. Kent's paper _Form Follows Feedback: Rethinking Cartographic Communication_, I was questioning 'what is the essence of cartography and mapping?'. In his paper, Alexander describes mapping and cartography as 'vehicle of communication' and mentions that they used to be merely an optimization of an effective map. However, as he mentions earlier, communication was the first paradigm to gain widespread acceptance amongst the
international cartographic community and I think that the essence of mapping does not necessarily have to reside under communication.  In another paper _Research Challenges in Geovisualization_, the author Alan M. MacEachren & Menno-Jan Kraak speaks to the cartography community about revising and improving geo-visualization techniques. However, I think what is important for us today is to not limit the essence of mapping as a tool of communication, but it is more important for us what is that we are mapping for and how geo-visualization could be applied in the other field.

Additionally, this would be a little bit off from the main topic of this week. Since the author of the paper _Form Follows Feedback: Rethinking Cartographic Communication_ is from a Christian school, I was wondering what are the mindset behind believing in both science and religion. In my opinion, they are both a kind of belief system, and I often hear conflicts between the two systems. In such a case, how do we convince that the two systems can coexist?  This is irrelevant from our course topics but if anyone is interested to talk about it, leave a comment!
