### ISSUE TITLE
Virtual Reality

### ISSUE THREAD

**Issue by jakobzhao** [jakobzhao/geog595#8]

**Comment by angellinn** [comment]
This week’s readings discuss the emerging concerns raised by the rapid development of cyborg and virtual reality products. Topics that are being discussed across the papers include: the sense of physical presence and SoE(Sense of Embodiment) in cyberspace, reframing gender identity in the 20th century, and potential sexist effects resulted from virtual reality product design. The papers intrigued me to rethink the definition of the sense of self-location, the sense of agency, and the sense of body ownership, and how the immersive virtual reality has unlimited potential of changing people’s traditional perception of physical presence, social presence, and self-presence. 

Among all, I like Haraway’s “An Ironic Dream of a Common Language for Women in the Integrated Circuit” the most in that she introduces cyborg as a metaphor to criticize traditional feminism and challenge Western patriarchal tenets. Instead of taking a scientific approach to interpret cyborg’s technological embodiment in the human body, Haraway takes a social and political approach to study cyborg’s presence in society and call an action for humans to revise the concept of gender and a reconstruction of identity. In her essay, Haraway introduces three boundary breakdowns since the 20th century that have reduced the separation between “human” from “animal” and “human” from “machine.” Eventually, she uses the figure of the cyborg to urge feminists to move beyond the limitations of traditional gender, feminism, and politics. Moving away from exclusive identification, individuals can now construct their own groups by choice. 

Since it’s possible to build VR using Raspberry Pi, these papers give me some guidance and inspiration for future projects related to creating a new physical experience in cyberspace.

**Comment by tpmccrea** [comment]
I found the pieces this week to be challenging, and thought-provoking. Though a range of topics were covered, the readings had shared themes of perception, embodiment, and human/machine distinctions. The pieces by Biocca (1997), Kilteni (2012), and Munafo (2017) were of particular interest since they were each written at different stages in the development of immersive VR tech, ranging from the proto-VR of the 90’s to new tech like the Oculus Rift headset. Although written over a span of 20 years, the authors are talking about many of the same concepts, and in the case of the Munafo, et al. piece, conducting a study with tangible data related to embodiment, and the gendered effects of wearable tech. Seeing the progression from a theoretical understanding of human interactions with immersive VR, to physical data derived from users experience in two decades shows just how fast all facets of digital tech are evolving.

The emergence of new tech allows us, to a degree, to assume the heretofore hypothesized form of a “cyborg”, which raises a number of difficult questions regarding what is “real” (simulacra and simulation), how our sense of being, and sense of embodiment changes when using VR, and what the physical and psychological effects are when we supersede, or augment our human form. While science-fiction often depicts cyborgs and human/tech integration as seamless, real world applications at present are still crude by comparison. A person's connection to the simulated world must be mediated by a headset, or other wearable device, which can result in feelings of disembodiment, disassociation, and nausea. 

To become “true” cyborg’s we need tech that gives the user a complete “Sense of Embodiment” as described by Kilteni. The creation of a device, or set of technology that allows for humans to have a “sense of self-location”, “sense of agency” and a “sense of human embodiment” would be an incredibly interesting development. How we adapt to, and utilize VR tech will have profound effects, particularly if we move beyond the current applications of VR, and individuals make wearable reality augmenting tech a part of their daily lives.

**Comment by erykwaligora** [comment]
The readings this week were somewhat surprising, meaning that I did not expect the discussion to take the direction that it did. Much of the conversation surrounding VR, especially in popular news articles or videos, involves the more economic, entertainment, and “futuristic” aspects of the technology. While these are valid discussion points, there is certainly more to be added to the conversation. Namely, the deep humanistic qualities that VR presents through its sense of space and place. The first reading by Munafo digs into the biological and physical experience of the user, specifically, how VR is experienced differently between the sexes. As the research shows, women have a higher rate of motion sickness when using a VR device than do men. This simple difference puts into question the viability for equality through this new technology. How can this technology be developed and used in a way that represents all users? Likewise, the other pieces centered around the idea of ‘embodiment’ gave me a lot to consider about the VR experience, especially concerning the individual. As of now, when using a VR device, the only real sense being used is sight (which of course limits the experience to those with the physical ability to see). The other senses are either not represented, or not well enough; hearing, smelling, tasting, and touching. So how does utilizing only one of five senses trigger a deeper sense of space and place? This question leaves me a bit skeptical. For me, until VR technology can address these other senses, an individual will continue to feel like he or she is still in their room where they have remained before, during, and after their VR experience. To elevate the senses in order to transport an individual into thinking that they themselves are truly in the space before their eyes would be a much more convincing experience. One key advancement would be the elimination of the goggles or face-mask. Although, a difficult feat, a VR world where I can see and interact with other users, feeling like myself (wearing my glasses), without a device on my head would be the ultimate experience.
