### ISSUE TITLE
Internet of Things

### ISSUE THREAD

**Issue by jakobzhao** [jakobzhao/geog595#9]

**Comment by weixingnie** [comment]
In these days, technology seems to become more and more portable than ever. According to the _Real-time GIS for smart cities_ "Today, information is indispensable to the successful management and operation of cities. Information is more abundant than ever before, due in part to the widespread adoption of computers, communication networks, and sensors", we are attempting to change the perspective of a city from full-scale to micro-scale of it. Making a further connection to our tutorial, the existence of raspberry pi is helping us to view our world from a much micro and detailed perspective. What does it mean "smart city"? It is a city that exploits technology in fields like urbanization, security, engagement, and management. Such a modern approach certainly complicates our city but it shrinks our acknowledgment of it.  Through real-time simulation, visualization of city data and GIS processing, we are democratizing the right of citizens, the scale of interaction, and the eyesight of foreseen. 

This viewpoint is also being notified by the article named "_A tetradic analysis of GIS and society using McLuhan’s law of the media_". GIS as a spatial database involving in the evolution of modern pop media, the shift of our society and the digital geographic information are approaching more and more to the cultural background and philosophical implication.

**Comment by jouho** [comment]
The concept of smart cities has been out there for a long time, and it is one of the hottest topics today in the scientific field. Toyota has recently announced the development of a smart city called "Woven city" and the realization of this smart city concept is about to come true. Meanwhile, Foucault's _Panopticism_ in _Discipline and Punish_ reminds us of what is behind building such cities. Foucault discusses Jeremy Bentham's Panopticon, a building with a tower at the center from which it is possible to see each cell in which a prisoner or schoolboy is incarcerated. Each individual in prison cells is seen but cannot communicate with the warders or other prisoners. The crowd is abolished. The panopticon induces a sense of permanent visibility that ensures the functioning of power. Moreover, the prisoner can always see the tower but never knows where he is being observed. This resembles a lot of smart cities that are being developed. The panopticon was built to make power more economic and effective. It does this to develop the economy, spread education and improves public morality, and so does a smart city. The residents are being monitored throughout their time in the city and never know when, where, what is being monitored. in _Real-time GIS for smart cities_ by Wenwen Li, Michael Batty & Michael F. Goodchild, it is mentioned how a wide range of information is real-time gathered to operate a smart city and such information gathering is what centralize the power of smart cities. While these cities are being built, it will inevitably raise awareness of information ethics and privacy. Personally, the biggest obstacle to build a smart city is how we deal with such problems.

**Comment by tpmccrea** [comment]
Perhaps because of the current discourse around the containment of the Coronavirus, I was particularly struck by the piece Panopticism by Michel Foucault. Foucault begins by reviewing an order from the 17th century detailing how to prevent the spread of plague through stringent quarantine, but also through surveillance and observation. In many ways the response to the current Coronavirus has taken a similar script as the procedures detailed by Foucault. However, instead of relying on a single syndic per street to observe and report changes in individuals' health, we have seen cities and countries harness the vast capabilities of the surveillance state to monitor and track infections, and an army of individuals with contactless thermometers to detect and isolate those who are ill. 

In many ways we are seeing in real time the development and implementation of the Panoptic qualities of the ‘Smart City’. The tools and infrastructure discussed by Li, et al. are actively being employed by countries like South Korea to harness and distribute a vast amount of information to a number of people. This raises a variety of concerns related to privacy, particularly concerning medical histories and records. While the development of the Smart City has shaped, and will continue to shape the operations of cities, through transportation modeling, planning, and economics, the technology can also be utilized to control, and surveille. Especially in times of crisis, we must be aware of how ostensibly helpful technology can be wielded to further entrench and project hegemonic power.
